### ISSUE TITLE
npm scripts not cross-platform

### ISSUE THREAD

**Issue by Focus3D** [atennert/hangman#13]
Hi,
I have a suggestion explained here https://techblog.dorogin.com/writing-cross-platform-npm-scripts-on-windows-79c510339ea6
So I used :
"devDependencies": {
 "@types/chai": "^4.1.1",
 "@types/mocha": "^2.2.46",
 "@types/node": "^8.0.53",
 "autoprefixer": "^7.1.6",
 "chai": "^4.1.2",
 "copyfiles": "^1.2.0", ****added
 "cssmin": "^0.4.3",
 "mkdirp": "^0.5.1", ****added
 "mocha": "^4.0.1",
 "node-sass": "^4.7.2", ****added
 "npm-run-all": "^4.1.2",
 "postcss-cli": "^4.1.1",
 "rimraf": "^2.6.2", ****added
 "sass-lint": "^1.12.1",
 "svgexport": "^0.3.2", ****added
 "ts-loader": "^3.2.0",
 "ts-mockito": "^2.2.7",
 "ts-node": "^3.3.0",
 "tslint": "^5.8.0",
 "typescript": "^2.6.2",
 "uglify-es": "^3.3.3",
 "webpack": "^3.10.0"
 },
 "dependencies": {
 "phantomjs-prebuilt": "^2.1.16" ****added
 }

**Comment by atennert** [comment]
Not going to handle this issue, since I'm fine with the current setup. It's my own experimental project.
